### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace' 

### ISSUE THREAD

**Issue by koreanjoker1983** [zaemyung/crawl-reuters#4]
I encountered "AttributeError: 'NoneType' object has no attribute 'replace' "
Could you help me to resolve this problem?

**Comment by zaemyung** [comment]
It seems the website has changed the layout of the page.
I have adjusted the codes to reflect the changes.
It seems to be working - but feel free to reopen the issue if the issue persists.

**Comment by zaemyung** [comment]
Close by be53f58
